### ISSUE TITLE
Missing extension module "lib/index.js"

### ISSUE THREAD

**Issue by anugrahandi** [Kaggle/jupyterlab#6]
Do the install inside Anaconda Command prompt and the following error occurs:

![Kaggle Jupyter Extension Install Error](https://user-images.githubusercontent.com/24928010/70629477-a213d880-1c5c-11ea-9f04-df092af51fe8.png)

And this is the log file:
```
Yarn configuration loaded.
Node v12.13.1

> "C:\Program Files\nodejs\npm.CMD" pack @kaggle/jupyterlab
npm notice 
npm notice package: @kaggle/jupyterlab@1.0.2
npm notice === Tarball Contents === 
npm notice 0      package           
npm notice 11.4kB LICENSE           
npm notice 2.6kB  package.json      
npm notice 2.9kB  README.md         
npm notice 0      schema            
npm notice 0      style             
npm notice 1.4kB  schema/kaggle.json
npm notice 856B   style/index.css   
npm notice 1.2kB  style/kaggle.svg  
npm notice === Tarball Details === 
npm notice name:          @kaggle/jupyterlab                      
npm notice version:       1.0.2                                   
npm notice filename:      kaggle-jupyterlab-1.0.2.tgz             
npm notice package size:  7.4 kB                                  
npm notice unpacked size: 20.2 kB                                 
npm notice shasum:        44466171399aee1e9781dda39cda2107ee16c240
npm notice integrity:     sha512-FJNJpxz8f8uZu[...]8oK51XDB1Ohdg==
npm notice total files:   9                                       
npm notice 
kaggle-jupyterlab-1.0.2.tgz

Traceback (most recent call last):

  File "C:\Users\user_name\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\user_name\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 93, in start
    ans = self.run_task()

  File "C:\Users\user_name\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 149, in run_task
    for i, arg in enumerate(self.extra_args)

  File "C:\Users\user_name\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 149, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "C:\Users\user_name\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 398, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "C:\Users\user_name\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 611, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "C:\Users\user_name\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1508, in _install_extension
    raise ValueError(msg % (extension, '\n'.join(messages)))

ValueError: "@kaggle/jupyterlab" is not a valid extension:
Missing extension module "lib/index.js"

Exiting application: jupyter
```

This is my versions:

> conda v 4.7.12
> npm v 6.12.1
> node v12.13.1
no yarn installed.

**Comment by peijenlin** [comment]
Hi @anugrahandi,

Thank you for reporting the issue.  This should be fixed by 1.0.3 release.

Please try again.

**Comment by anugrahandi** [comment]
Tested and installer works. Thank you.

**Comment by mahimakaushik-oss** [comment]
i am also getting the same issue... can anyone help me please
Missing extension module "lib/index.js"
See the log file for details:  /tmp/jupyterlab-debug-jeki4eor.log
thanks in advance.
