### ISSUE TITLE
ValueError: "@kaggle/jupyterlab" is not a valid npm package

### ISSUE THREAD

**Issue by sandervh14** [Kaggle/jupyterlab#8]
Hi,

I found your extension through this article: https://www.kaggle.com/product-feedback/117903.

By launching `jupyter labextension install @kaggle/jupyterlab`, I was not able to install this jupyterlab extension, I get the error: `ValueError: "@kaggle/jupyterlab" is not a valid npm package`.

This was the full error log:

```
Node v10.13.0

Yarn configuration loaded.
> C:\Users\sander.vandenhautte\Anaconda3\envs\kaggle-dsc\npm.CMD pack @kaggle/jupyterlab
npm ERR! code E404
npm ERR! 404 Not Found: @kaggle/jupyterlab@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sander.vandenhautte\AppData\Roaming\npm-cache\_logs\2021-03-01T14_08_27_964Z-debug.log

Traceback (most recent call last):

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 93, in start
    ans = self.run_task()

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 138, in run_task
    return any([

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 139, in <listcomp>
    install_extension(

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 603, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1499, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1578, in _extract_package
    raise ValueError(msg % source)

ValueError: "@kaggle/jupyterlab" is not a valid npm package

Exiting application: jupyter
```

I saw that the above nodejs version was rather low though, so I deinstalled it and installed nodejs from the conda-forge channel, but then again got the same error.
Full log of that:

```
Node v15.10.0

Yarn configuration loaded.
> C:\Users\sander.vandenhautte\Anaconda3\envs\kaggle-dsc\npm.CMD pack @kaggle/jupyterlab
npm notice 
npm notice New minor version of npm available! 7.5.3 -> 7.6.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.6.0>
npm notice Run `npm install -g npm@7.6.0` to update!
npm notice 
npm notice 
npm notice New minor version of npm available! 7.5.3 -> 7.6.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.6.0>
npm notice Run `npm install -g npm@7.6.0` to update!
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@kaggle%2fjupyterlab - Not found
npm ERR! 404 
npm ERR! 404  '@kaggle/jupyterlab@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sander.vandenhautte\AppData\Local\npm-cache\_logs\2021-03-01T14_16_39_788Z-debug.log

Traceback (most recent call last):

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 93, in start
    ans = self.run_task()

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 138, in run_task
    return any([

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 139, in <listcomp>
    install_extension(

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 603, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1499, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "C:\Users\sander.vandenhautte\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1578, in _extract_package
    raise ValueError(msg % source)

ValueError: "@kaggle/jupyterlab" is not a valid npm package

Exiting application: jupyter
```

I also can't find the extension when I browse manually through the extension tab on the left on JupyterLab's GUI, nor can I find your package manually in the npm package repository (https://www.npmjs.com/search?q=kaggle).
Could it be that this extension has been discontinued? It looked like a nice idea to me though.

Kind regards.

**Comment by stannnman** [comment]
+1

Love the idea but also getting this problem when I try to install.
